name: ssiteverifund
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: Pixelify # The nickname you'll reference in Dart code
      fonts:
        - asset: lib/assets/Pixelify_Sans/PixelifySans-VariableFont_wght.ttf
    - family: Press # The nickname you'll reference in Dart code
      fonts:
        - asset: lib/assets/Press_Start_2P/PressStart2P-Regular.ttf
    - family: Space # The nickname you'll reference in Dart code
      fonts:
        - asset: lib/assets/Space_Mono/SpaceMono-Regular.ttf
        - asset: lib/assets/Space_Mono/SpaceMono-Bold.ttf
        - asset: lib/assets/Space_Mono/SpaceMono-Italic.ttf
        - asset: lib/assets/Space_Mono/SpaceMono-BoldItalic.ttf